export const TIPOS_OCORRENCIA = [
  "Plantio efetuado",
  "Acompanhamento pós-plantio",
  "Germinação avaliada",
  "Falha de plantio",
  "Ataque de lagarta",
  "Ataque de cigarrinha",
  "Ataque de percevejo",
  "Ataque de pulgão",
  "Presença de plantas daninhas",
  "Doença foliar",
  "Mancha foliar",
  "Ferrugem",
  "Deficiência nutricional",
  "Estresse hídrico",
  "Solo compactado",
  "Necessidade de dessecação",
  "Necessidade de replantio",
  "Adubação de base realizada",
  "Adubação de cobertura realizada",
  "Adubação foliar realizada",
  "Pulverização realizada",
  "Aplicação de herbicida",
  "Aplicação de inseticida",
  "Aplicação de fungicida",
  "Calagem",
  "Gessagem",
  "Gradagem",
  "Subsolagem",
  "Reforma de pastagem",
  "Pastejo excessivo",
  "Baixa rebrota",
  "Excesso de invasoras na pastagem",
  "Outro",
];
